#!/bin/bash
#
# This file is part of project link.developers/pylonsdk.
# It is copyrighted by the contributors recorded in the version control history of the file,
# available from its original location https://gitlab.com/link.developers/recipes-externals/pylonsdk.
#
# SPDX-License-Identifier: MPL-2.0


c_compiler:
  - gcc
target_platform:
  - linux-aarch64
c_compiler_version:
  - 7.2.0

cxx_compiler:
  - gxx
target_platform:
  - linux-aarch64
cxx_compiler_version:
  - 7.2.0
